name: grocery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  carousel_slider: ^4.1.1
  google_maps_flutter: ^2.2.0
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  proste_bezier_curve: ^2.0.2
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.15
  intl_phone_number_input: ^0.7.0+2
  splashscreen: ^1.3.5
  flutter_svg: ^1.1.4
  shimmer: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  flutter_slidable: any
  permission_handler: ^10.2.0
  notification_permissions: ^0.6.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
  #   - images/a_dot_ham.jpeg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: dmSans
  #     fonts:
  #       - asset: assets/fonts/1DMSans-Medium.ttf
  #       - asset: assets/fonts/DMSans-Medium.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
